apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-dev

bases:
  - ../../base

# Override image tag (Jenkins replaces IMAGE_TAG_PLACEHOLDER)
images:
  - name: your-dockerhub-username/todo-api
    newTag: IMAGE_TAG_PLACEHOLDER

# Dev: 1 replica is fine
patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: todo-api

configMapGenerator:
  - name: todo-api-config
    behavior: merge
    literals:
      - NODE_ENV=development
      - APP_VERSION=dev
